name: ChatPing
author: Lee Neighoff
version: 2023.10.08-R1
api-version: 1.20
main: com.muricagaming.chatping.Main

description: "§7Configurable chat mentions plugin.§r\n§bSupport the author!§r\n§7https://ko-fi.com/leeneighoff§r"

commands:
    chatping:
        description: Main plugin command
        aliases: [cping]
        permission: chatping.user

permissions:
    chatping.*:
        description: Grants full administrative capabilities.
        default: op
        children:
            chatping.user: true
            chatping.admin: true
    chatping.user:
        description: Grants ability to be pinged as well as access to prefs argument.
        default: op
    chatping.admin:
        description: Grants access to defaults and override arguments.
        default: op