name: ChatPing
author: Lee Neighoff
version: 2023.10.08-R1
api-version: 1.20
main: com.muricagaming.chatping.Main

description: "§7Configurable chat mentions plugin.§r\n§bSupport the author!§r\n§7https://ko-fi.com/leeneighoff§r"

commands:
    chatping:
        description: Main plugin command
        aliases: [cping]
        permission: chatping.admin

permissions:
    chatping.*:
        description: Grants full administrative capabilities.
        default: op
        children:
            chatping.ping: true
            chatping.alias: true
            chatping.admin: true
    chatping.ping:
        default: true
    chatping.toggle:
        default: true
    chatping.alias:
        default: op