name: ChatPing
author: Lee Neighoff
version: 2023.10.07
api-version: 1.20
main: com.muricagaming.chatping.Main

description: Notifies players when they're mentioned in chat.

commands:
    chatping:
        description: Main plugin command
        aliases: [cping]
        permission: chatping.admin

permissions:
    chatping.*:
        description: Grants full administrative capabilities.
        default: op
        children:
            chatping.ping: true
            chatping.alias: true
            chatping.admin: true
    chatping.ping:
        default: true
    chatping.toggle:
        default: true
    chatping.alias:
        default: op